export const board = [
    {
        row: 6,
        column: 1,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 2,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 3,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 4,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 5,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 5,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 4,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 3,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 2,
        column: 6,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 1,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 0,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 0,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    // red home
    {
        row: 1,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    {
        row: 2,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    {
        row: 3,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    {
        row: 4,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    {
        row: 5,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'red',
    },
    // red home ends
    {
        row: 0,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 1,
        column: 8,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 2,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 3,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 4,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 5,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },

    {
        row: 6,
        column: 9,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 10,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 11,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 12,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 13,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 6,
        column: 14,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 7,
        column: 14,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    // green home
    {
        row: 7,
        column: 13,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    {
        row: 7,
        column: 12,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    {
        row: 7,
        column: 11,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    {
        row: 7,
        column: 10,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    {
        row: 7,
        column: 9,
        isStar: false,
        tokens: [],
        turn: 'green',
    },
    // green home ends
    {
        row: 8,
        column: 14,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 13,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 12,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 11,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 10,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 9,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 9,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 10,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 11,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 12,
        column: 8,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 13,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 14,
        column: 8,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 14,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    // yellow home
    {
        row: 13,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    {
        row: 12,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    {
        row: 11,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    {
        row: 10,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    {
        row: 9,
        column: 7,
        isStar: false,
        tokens: [],
        turn: 'yellow',
    },
    // yellow home ends
    {
        row: 14,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 13,
        column: 6,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 12,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 11,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 10,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 9,
        column: 6,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 5,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 4,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 3,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 2,
        isStar: true,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 1,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 8,
        column: 0,
        isStar: false,
        tokens: [],
        turn: null,
    },
    {
        row: 7,
        column: 0,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    // blue home 
    {
        row: 7,
        column: 1,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    {
        row: 7,
        column: 2,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    {
        row: 7,
        column: 3,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    {
        row: 7,
        column: 4,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    {
        row: 7,
        column: 5,
        isStar: false,
        tokens: [],
        turn: 'blue',
    },
    // blue home ends
    {
        row: 6,
        column: 0,
        isStar: false,
        tokens: [],
        turn: null,
    },
];